import { AnimatePresence, motion } from "framer-motion";
import Head from "next/head";
import { pageTransition } from "../animations";
import { Events, Hero, Message } from "../containers";
import { Navbar } from "../components";

const Home = () => {
  return (
    <AnimatePresence exitBeforeEnter>
      <Navbar />
      <motion.section
        variants={pageTransition}
        initial="hidden"
        animate="visible"
        exit="exit"
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero />
        <Events />
        <Message />
      </motion.section>
    </AnimatePresence>
  );
};

export default Home;
