import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl text-red-500 font-josefin">
          Welcome to <a href="https://nextjs.org">Welcome to Techelons22</a>
        </h1>
      </main>
    </div>
  );
}
