import { AnimatePresence, motion } from "framer-motion";
import Head from "next/head";
import { pageTransition } from "../animations";
import { Events, Hero, Message } from "../containers";
import { Navbar } from "../components";
import { Parallax } from "react-scroll-parallax";

const Home = () => {
  return (
    <AnimatePresence exitBeforeEnter>
      <Navbar />
      <motion.section
        variants={pageTransition}
        initial="hidden"
        animate="visible"
        exit="exit"
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Parallax
          speed={-20}
          rotate={[-100, 20]}
          rotateZ={[-100, 20]}
          className="absolute top-[34rem] left-[5rem] md:left-[14rem] -z-50"
        >
          <img
            src="./images/code.svg"
            alt="Code"
            className="opacity-90 h-10 sm:h-20"
          />
        </Parallax>
        <Parallax
          speed={10}
          rotate={[-100, 100]}
          rotateZ={[-100, 100]}
          className="absolute top-[36rem] right-[2rem] md:right-[14rem] -z-50"
        >
          <img
            src="./images/cpu.svg"
            alt="cpu"
            className=" top-[20rem] left-[8rem] opacity-30 h-15"
          />
        </Parallax>
        <Parallax speed={20} className="absolute top-[78rem] right-[12rem]">
          <img
            src="./images/laptop.svg"
            alt="laptop"
            className="opacity-30 h-20"
          />
        </Parallax>
        <Parallax speed={-20} className="absolute top-[71rem] left-[12rem]">
          <img
            src="./images/drive.svg"
            alt="drive"
            className="opacity-30 h-10"
          />
        </Parallax>
        <Parallax
          speed={30}
          className="absolute top-[84rem] left-[2rem] -z-50"
        >
          <img src="./images/cpu.svg" alt="cpu" className="opacity-40 h-15" />
        </Parallax>

        <Hero />
        <Events />
        <Message />
      </motion.section>
    </AnimatePresence>
  );
};

export default Home;
